name: build and release

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: Install PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        
    - name: Install composer dependencies
      run: composer i
          
    - name: install yarn
      run: npm install -g yarn
      
    - name: install WP-CLI
      run: |
        curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
        php wp-cli.phar --info
        chmod +x wp-cli.phar
        sudo mv wp-cli.phar /usr/local/bin/wp

    - name: Install ZIP
      run: sudo apt-get install zip
        
    - name: Build
      run: |
        yarn --ignore-engines
        yarn release
        
    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: article-generator
        path: |
          dist/*.zip
          !dist/**/*.md
          
    - name: upload release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "article-generator.zip"
        prerelease: true
