name: PHPUnit Tests

on:
    pull_request:
    push:
        branches:
            - trunk
            - develop
            - main

# Cancels all previous workflow runs for pull requests that have not completed.
concurrency:
    # The concurrency group contains the workflow name and the branch name for pull requests
    # or the commit hash for any other events.
    group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
    cancel-in-progress: true

jobs:
    test:
        name: phpunit tests
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false

        steps:
            - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # v2.3.4

            - name: Use desired version of php (7.4 with xdebug)
              uses: shivammathur/setup-php@v2
              with:
                  php-version: '7.4'
                  coverage: xdebug

            - name: Composer install and build
              run: |
                  composer install
                  composer update
                  composer dump-autoload -o

            - name: Running the phpunit tests
              continue-on-error: true
              run: composer run test
